### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by kankaristo** [tyage/video-player#16]
The feature to show the video in the background is great, but I would prefer to open the video in a new tab.

Could this be available as a config option?

P.S.
Thanks for a great package! :)

**Comment by tyage** [comment]
Your recommendation is interensting.
How about creating a new command: `Play in a new tab` instead of creating a config option?

**Comment by kankaristo** [comment]
Yeah, that would work too, then you could use both. :+1:

Is it possible for video-player to handle a file opened by Atom? So that you would just use Atom's own "Open file" and it would open in video-player (in a new tab).

This is how the "audio" and "ogg-preview" packages do it, and video-player seems to handle audio as well. I use Atom mostly for game development, and this would be really useful for previewing sound effects, music, cutscene videos, etc. directly in Atom. :)

**Comment by tyage** [comment]
> Is it possible for video-player to handle a file opened by Atom? So that you would just use Atom's own "Open file" and it would open in video-player (in a new tab).
> This is how the "audio" and "ogg-preview" packages do it, and video-player seems to handle audio as well. I use Atom mostly for game development, and this would be really useful for previewing sound effects, music, cutscene videos, etc. directly in Atom. :)

Yes, it may be useful if this package handles a file opened by Atom.

`audio` and `ogg-preview` packages check file extension, then handle the file.
Problem is that `video-player` doesn't check file extension because it handles .mp4, .mp3, .ogg, .mov, .ts, .wav, etc... 
(I don't know all file extensions that HTML5 video element and VLC can handle!)
So I will work and it will be able to handle most of files correctly by checking it in some way, but it can be incomplete.(Some videos are not played)

I didn't expect that this package is used for game development, so thank you for your pointing out!

**Comment by kankaristo** [comment]
You could make it so that `video-player:play` tries to open everything, but have a list of extensions of files which should be opened with Atom's own "open file"?

**Comment by tyage** [comment]
`video-player:play` tries to open everything, because it should treat many types of files.
If we should treat Atom's own "open file" ( as `audio` and `ogg-preview` packages do ), we should check extension or mimetype of the file to avoid playing video with the text file.

This package uses HTML5 video and VLC.
And VLC can play many types of files as below.
https://wiki.videolan.org/VLC_Features_Formats
